[package]
name = "nativelink-metric-macro-derive"
version = "0.4.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# TODO(allada) We currently need to pin these to specific version.
# Some down-stream can't be upgraded just yet.
proc-macro2 = { version = "=1.0.86", features = ["proc-macro", "span-locations"] }
quote = "=1.0.36"
syn = { version = "=2.0.68", features = ["extra-traits", "full", "fold"] }
