[workspace]
resolver = "2"

[package]
name = "nativelink"
version = "0.4.0"
edition = "2021"
rust-version = "1.79.0"

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = false
opt-level = 0
strip = false
debug = true

# Prefer this profile in CI, for instance via `cargo test --all --profile=smol`.
# It reduces the size of the `target` directory from ~12GB to ~1GB.
[profile.smol]
inherits = "dev"
opt-level = "z"
strip = true
debug = false

[[bin]]
name = "nativelink"

[features]
enable_tokio_console = []

[dependencies]
nativelink-error = { path = "nativelink-error" }
nativelink-proto = { path = "nativelink-proto" }
nativelink-config = { path = "nativelink-config" }
nativelink-scheduler = { path = "nativelink-scheduler" }
nativelink-service = { path = "nativelink-service" }
nativelink-store = { path = "nativelink-store" }
nativelink-util = { path = "nativelink-util" }
nativelink-worker = { path = "nativelink-worker" }
nativelink-metric = { path = "nativelink-metric" }
nativelink-metric-collector = { path = "nativelink-metric-collector" }

async-lock = "3.3.0"
axum = "0.6.20"

clap = { version = "4.5.4", features = ["derive"] }
futures = "0.3.30"
hyper = { version = "0.14.28" }
mimalloc = "0.1.41"
parking_lot = "0.12.2"
rustls-pemfile = "2.1.2"
scopeguard = "1.2.0"
serde_json5 = "0.1.0"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "signal"] }
tokio-rustls = "0.25.0"
tonic = { version = "0.11.0", features = ["gzip", "tls"] }
tower = "0.4.13"
tracing = "0.1.40"
opentelemetry_sdk = { version = "0.23.0", features = ["metrics"] }
tracing-subscriber = "0.3.18"
opentelemetry = { version = "0.23.0", features = ["metrics"] }
prometheus = "0.13.4"
opentelemetry-prometheus = "0.16.0"
serde_json = "1.0.120"
