[workspace]
resolver = "2"

[package]
name = "nativelink"
version = "0.2.0"
edition = "2021"
rust-version = "1.76"

[profile.release]
lto = true
opt-level = 3

# Prefer this profile in CI, for instance via `cargo test --all --profile=smol`.
# It reduces the size of the `target` directory from ~12GB to ~1GB.
[profile.smol]
inherits = "release"
lto = "thin"
opt-level = "z"
strip = true

[[bin]]
name = "nativelink"

[features]
enable_tokio_console = []

[dependencies]
nativelink-error = { path = "nativelink-error" }
nativelink-proto = { path = "nativelink-proto" }
nativelink-config = { path = "nativelink-config" }
nativelink-scheduler = { path = "nativelink-scheduler" }
nativelink-service = { path = "nativelink-service" }
nativelink-store = { path = "nativelink-store" }
nativelink-util = { path = "nativelink-util" }
nativelink-worker = { path = "nativelink-worker" }

async-lock = "3.3.0"
axum = "0.6.20"
clap = { version = "4.5.4", features = ["derive"] }
console-subscriber = { version = "0.2.0" }
futures = "0.3.30"
hyper = { version = "0.14.28" }
mimalloc = "0.1.39"
parking_lot = "0.12.1"
prometheus-client = "0.21.2"
rustls-pemfile = "2.1.1"
scopeguard = "1.2.0"
serde_json5 = "0.1.0"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "signal", "rt"] }
tokio-rustls = "0.25.0"
tonic = { version = "0.11.0", features = ["gzip", "tls"] }
tower = "0.4.13"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
