[package]
name = "nativelink-service"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-proto = { path = "../nativelink-proto" }
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-store = { path = "../nativelink-store" }
nativelink-scheduler = { path = "../nativelink-scheduler" }

bytes = "1.6.0"
futures = "0.3.30"
hyper = { version = "0.14.28" }
serde_json5 = "0.1.0"
parking_lot = "0.12.2"
prost = "0.12.4"
rand = "0.8.5"
tokio = { version = "1.37.0", features = ["sync", "rt"] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tonic = { version = "0.11.0", features = ["gzip", "tls"] }
tower = "0.4.13"
tracing = "0.1.40"
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
nativelink-macro = { path = "../nativelink-macro" }
nativelink-metric = { path = "../nativelink-metric" }

async-trait = "0.1.80"
async-lock = "3.3.0"
hyper = "0.14.28"
maplit = "1.0.2"
pretty_assertions = "1.4.0"
prost-types = "0.12.4"
