[package]
name = "nativelink-metric"
version = "0.4.0"
edition = "2021"

[dependencies]
nativelink-metric-macro-derive = { path = "nativelink-metric-macro-derive" }

async-lock = "3.3.0"
parking_lot = "0.12.2"
tracing = "0.1.40"
tokio = { version = "1.37.0", features = ["sync"] }
