[package]
name = "nativelink-metric-collector"
version = "0.4.0"
edition = "2021"
rust-version = "1.79.0"

[dependencies]
nativelink-metric = { path = "../nativelink-metric" }

opentelemetry = { version = "0.23.0", features = ["metrics"] }
parking_lot = "0.12.2"
serde = "1.0.204"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
nativelink-error = { path = "../nativelink-error" }

opentelemetry_sdk = { version = "0.23.0", features = ["metrics"] }
opentelemetry-prometheus = "0.16.0"
prometheus = "0.13.4"
serde_json = "1.0.120"
